# Generated by Django 5.0.6 on 2024-05-15 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='in_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bike',
            name='type',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
