# Generated by Django 5.0.6 on 2024-05-15 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0002_bike_in_stock_bike_type_customer_name_order_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='type',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order',
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_system.bike'),
        ),
    ]
