# Generated by Django 5.0.6 on 2024-05-15 20:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0003_rename_type_bike_item_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bike',
            new_name='Transport',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
