# Generated by Django 5.0.6 on 2024-05-16 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_system', '0004_rename_bike_transport_alter_order_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transport',
            new_name='Inventory',
        ),
    ]
